<?php
?>
<!-- jouw HTML met de inhoud over onderwerp 3 komt hier... -->
<div>
    <h1>Re:Zero</h1>
    <img src="images/re-zero.jpg" class="subjectImage">
    <p class="information">Re:Zero − Starting Life in Another World (Japanese: Re:ゼロから始める異世界生活, Hepburn: Re:Zero kara Hajimeru Isekai Seikatsu), often referred to simply as Re:Zero and also known as Re: Life in a different world from zero,[d] is a Japanese light novel series written by Tappei Nagatsuki and illustrated by Shin'ichirō Ōtsuka. The story centers on Subaru Natsuki, a hikikomori who suddenly finds himself transported to another world on his way home from the convenience store. The series was initially serialized on the website Shōsetsuka ni Narō from 2012 onwards. Thirty-two light novels, as well as five side story volumes and eight short story collections have been published by Media Factory under their MF Bunko J imprint.

The series' first three arcs have been adapted into separate manga series. The first, by Daichi Matsue, was published between June 2014 and March 2015. The second, by Makoto Fugetsu, has been published by Square Enix since October 2014. Matsue launched the third adaptation, also published by Media Factory, in May 2015. Additionally, Media Factory has published two anthology manga with stories by different artists. An anime television series adaptation produced by White Fox aired from April to September 2016, starting with an hour-long special. The first of two OVA based on the series was released in October 2018, and the second OVA was released in November 2019. In March 2017, game developer 5pb. released a visual novel based on the series. A second season aired in a split-cour format, with the first half airing from July to September 2020, and the second half airing from January to March 2021.

The novels and all three manga adaptations are published in North America by Yen Press. The anime adaptation has been licensed by Crunchyroll outside Asia, which released the anime on home video through Funimation in the United States and Anime Limited in the United Kingdom. In Southeast Asia and South Asia, the series is licensed by Muse Communication.

The light novels have sold more than 11 million copies, while the anime series has sold more than 70,000 copies on home video. The light novels have been praised for their fresh take on the "another world" concept, but have been criticized for awkward dialogue and redundancy. The series has been praised by critics for its fleshed-out characters, complex world and lore, and thought-provoking topics and themes. The series received awards at the 2015–2016 Newtype Anime Awards and the 2017 Sugoi Japan Awards, and was nominated for Anime of the Year at the 1st Crunchyroll Anime Awards.</p>
</div>